sudo: false
dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_deploy:
  - pip install --upgrade pip
  - pip install poetry
  - poetry config http-basic.pypi $PYPI_USER $PYPI_PASS
  - poetry build
deploy:
  provider: script
  script: poetry publish
  skip_existing: true
  on:
    tags: true
env:
  global:
    - CC_TEST_REPORTER_ID=987f85840846e90736b3e4243b87a441e6286ccb26d9dca056d0071e0857a108
install:
  - pip install --upgrade pip
  - pip install poetry
  - poetry install -v
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - "./cc-test-reporter before-build"
script:
  - poetry run py.test --cov=tweet_delete --cov-report xml
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"
